apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-obj-dump-cr
  labels:
    app: k8s-obj-dump
    name: k8s-obj-dump
rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs: ["get", "list", "watch"]
  - nonResourceURLs:
    - '*'
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-obj-dump-crb
  labels:
    app: k8s-obj-dump
    name: k8s-obj-dump
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-obj-dump-cr
subjects:
- kind: ServiceAccount
  name: default
  namespace: tanzu-workload
